#!/usr/bin/env bash
# This script lists all currently running processes including background processes in a user-friendly format

ps -e --forest -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
